apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner # no dynamic provisioning 
reclaimPolicy: Retain # default: delete
allowVolumeExpansion: true
mountOptions:
  - rw # default
volumeBindingMode: WaitForFirstConsumer

